#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_i2c.h"
#include "stm32f4xx_usart.h"

// SI5351 register map generated by ClockBuilder
// (only for initial test, probably not going to be actually used)
#define code
#include "register_map.h"
#undef code

void SystemInit() {
}

const uint8_t addr_synth = 0x60; // SI5351 synthesizer I2C address
const uint8_t addr_rfc = 0x1A;   // WM8731 used for zero-IF signal
const uint8_t addr_afc = 0x1B;   // WM8731 used for microphone and headphone audio

int i2cdelay = 20;
void i2c_delay() {
	int d;
	for(d = 0; d < i2cdelay; d++) __asm("nop");
}

// SCL 8, SDA 9
#define I2C_SCL 0x100
#define I2C_SDA 0x200

void writereg(uint8_t addr, uint8_t reg, uint8_t v) {
	int i;
	uint32_t odr = GPIOB->ODR & (~(I2C_SCL | I2C_SDA));
	uint32_t allbits;
	// start
	GPIOB->ODR = odr | I2C_SCL;
	i2c_delay();
	GPIOB->ODR = odr;
	i2c_delay();

	allbits =
	(addr << (9*2+2)) | (0 << (9*2+1)) | (1 << (9*2)) |
	(reg  << (9*1+1)) |                  (1 << (9*1)) |
	(v    << (9*0+1)) |                  (1 << (9*0));
	for(i = 0; i < 9*3; i++) {
		uint32_t odr_bit;
		if(allbits & (1 << (9*3-1)))
			odr_bit = odr | I2C_SDA;
		else
			odr_bit = odr;
		allbits <<= 1;
		// send bit
		GPIOB->ODR = odr_bit;
		i2c_delay();
		GPIOB->ODR = odr_bit | I2C_SCL;
		i2c_delay();
		GPIOB->ODR = odr_bit;
		i2c_delay();
	}

	// stop
	GPIOB->ODR = odr | I2C_SCL;
	i2c_delay();
	GPIOB->ODR = odr | I2C_SCL | I2C_SDA;
	i2c_delay();
}


int usart_enabled = 0;
void print(char *data) {
	/* Send text to USART1 */
	if(usart_enabled == 0) return;
	for(; *data != '\0'; data++) {
		/*while(!USART_GetFlagStatus(USART1, USART_FLAG_TXE));
		USART_SendData(USART1, (uint8_t)*data);*/
		while(!(USART1->SR & USART_SR_TXE));
		USART1->DR = (uint8_t)*data;
		//ITM_SendChar(*data);
	}
}

void assert_failed(uint8_t *file, uint32_t line) {
	char l[9] = "      \r\n";
	print("\r\nAssert failed: ");
	print((char*)file);
	l[5] = '0' + line % 10;
	l[4] = '0' + (line / 10) % 10;
	l[3] = '0' + (line / 100) % 10;
	l[2] = '0' + (line / 1000) % 10;
	l[1] = '0' + (line / 10000);
	print(l);
}

// The WM8731 registers have 7-bit addresses and 9-bit data
// so the highest data bit of each register
// is in lowest bit of the first byte.
#define RFC_INIT_SIZE 11
const uint8_t rfc_init[RFC_INIT_SIZE][2] = {
{0x1E, 0x00}, // reset it first
{0x00, 0x1F}, // maximum L line input volume, no mute
{0x02, 0x1F}, // maximum R line input volume, no mute
{0x04, 0x7F}, // maximum L headphone volume
{0x06, 0x7F}, // maximum R headphone volume
{0x08, (1<<1) | (0<<2)}, // mute mic in, line input to ADC
{0x0A, (1<<0) | (0<<1)}, // disable ADC highpass, disable de-emphasis
{0x0C, (1<<1)}, // power down mic bias
{0x0E, (2<<0) | (0<<2) | (0<<6)}, // I2S format, 16-bit input audio data, slave mode
{0x10, 0b0000<<2}, // (256fs oversampling, no frequency dividers), 48 kHz ADC and DAC
{0x12, 0x01} // activate interface
};


#define TFT_SPI SPI1
#define TFT_CS_GPIO GPIOB
#define TFT_CS_Pin GPIO_Pin_6
#define TFT_DC_Pin GPIO_Pin_4

void tft_send(uint8_t *bytes, int n, int dc) {
	int i;
	if(dc) // data
		TFT_CS_GPIO->ODR |= TFT_DC_Pin;
	else // command
		TFT_CS_GPIO->ODR &= ~TFT_DC_Pin;
	TFT_CS_GPIO->ODR &= ~TFT_CS_Pin;
	for(i = 0; i < n; i++) {
		while(!SPI_I2S_GetFlagStatus(TFT_SPI, SPI_I2S_FLAG_TXE));
		SPI_I2S_SendData(TFT_SPI, bytes[i]);
	}
	while(SPI_I2S_GetFlagStatus(TFT_SPI, SPI_I2S_FLAG_BSY));
	TFT_CS_GPIO->ODR |= TFT_CS_Pin;
}


void tft_data(uint8_t *data, int ndata, int first_byte_is_command) {
	if(first_byte_is_command) {
		tft_send(data, 1, 0);
		tft_send(data+1, ndata-1, 1);
	} else {
		tft_send(data, ndata, 1);
	}
}



int main() {
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE);

	// bit banged I2C pins
	GPIO_Init(GPIOB, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_8 | GPIO_Pin_9,
		.GPIO_Mode = GPIO_Mode_OUT,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_OD,
		.GPIO_PuPd = GPIO_PuPd_UP
	});

	// init SI5351
	int reg_i;
	for(reg_i = 0; reg_i < NUM_REGS_MAX; reg_i++) {
		writereg(addr_synth, Reg_Store[reg_i].Reg_Addr, Reg_Store[reg_i].Reg_Val);
	}

	// init RF WM8731
	for(reg_i = 0; reg_i < RFC_INIT_SIZE; reg_i++) {
		writereg(addr_rfc, rfc_init[reg_i][0], rfc_init[reg_i][1]);
	}


	// USART1 initialization
	// External USB-UART converter is connected to PA9
	// because the built-in converter on Nucleo board in USART2
	// seems to work poorly.
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource9, GPIO_AF_USART1); // USART1_TX
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource10, GPIO_AF_USART1); // USART1_RX
	GPIO_Init(GPIOA, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_10,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_UP
	});
	USART_Init(USART1, &(USART_InitTypeDef) {
		.USART_BaudRate = 115200,
		.USART_WordLength = USART_WordLength_8b,
		.USART_StopBits = USART_StopBits_1,
		.USART_Parity = USART_Parity_No,
		.USART_Mode = USART_Mode_Tx | USART_Mode_Rx,
		.USART_HardwareFlowControl = USART_HardwareFlowControl_None
	});
	USART_Cmd(USART1, ENABLE);
	usart_enabled = 1;
	print("\r\nHello world\r\n");


	// SPI1 initialization
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1, ENABLE);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource5, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource6, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource7, GPIO_AF_SPI1);
	GPIO_Init(GPIOA, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

	GPIO_Init(TFT_CS_GPIO, &(GPIO_InitTypeDef) {
		.GPIO_Pin = TFT_CS_Pin | TFT_DC_Pin,
		.GPIO_Mode = GPIO_Mode_OUT,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

	SPI_Init(SPI1, &(SPI_InitTypeDef) {
		.SPI_Direction = SPI_Direction_1Line_Tx,
		.SPI_Mode = SPI_Mode_Master,
		.SPI_DataSize = SPI_DataSize_8b,
		.SPI_CPOL = SPI_CPOL_Low,
		.SPI_CPHA = SPI_CPHA_1Edge,
		.SPI_NSS = SPI_NSS_Soft,
		.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_16,
		.SPI_FirstBit = SPI_FirstBit_MSB,
		.SPI_CRCPolynomial = 7 // default value
	});
	SPI_Cmd(SPI1, ENABLE);

	// I2S PLL initialization
	RCC_PLLI2SCmd(DISABLE); // PLLI2SConfig should be called with PLLI2S disabled

	// PLLI2S clock source is common with main PLL configured with RCC_PLLConfig.
	// Using 26 MHz clock input (HSE)
	RCC_HSEConfig(RCC_HSE_Bypass);
	print("Waiting for HSE\r\n");
	RCC_WaitForHSEStartUp();
	print("HSE started up\r\n");

	RCC_PLLConfig(RCC_PLLSource_HSE, 13, 50, 2, 4);
	RCC_PLLCmd(ENABLE);

	RCC_I2SCLKConfig(RCC_I2S2CLKSource_PLLI2S);
	RCC_PLLI2SConfig(72,3);
	RCC_PLLI2SCmd(ENABLE);

	print("Waiting for PLLI2S\r\n");
	while(!RCC_GetFlagStatus(RCC_FLAG_PLLI2SRDY));
	print("PLLI2S ready\r\n");

	// I2S2 initialization
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_SPI2, ENABLE); // I2S2
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource12, GPIO_AF_SPI2); // I2S2_WS
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource13, GPIO_AF_SPI2); // I2S2_CK
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource15, GPIO_AF_SPI2); // I2S2_SD
	GPIO_PinAFConfig(GPIOC, GPIO_PinSource6,  GPIO_AF_SPI2); // I2S2_MCK
	GPIO_Init(GPIOB, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_15,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});
	GPIO_Init(GPIOC, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_PinSource6,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

	I2S_Init(SPI2, &(I2S_InitTypeDef) {
		.I2S_Mode = I2S_Mode_MasterTx,
		.I2S_Standard = I2S_Standard_Phillips,
		.I2S_DataFormat = I2S_DataFormat_16b,
		.I2S_MCLKOutput = I2S_MCLKOutput_Enable,
		.I2S_AudioFreq = I2S_AudioFreq_48k,
		.I2S_CPOL = I2S_CPOL_Low
	});
	I2S_Cmd(SPI2, ENABLE);


	// I2S3 initialization
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_SPI3, ENABLE); // I2S3
	GPIO_PinAFConfig(GPIOC, GPIO_PinSource10, GPIO_AF_SPI3); // I2S3_CK
	GPIO_PinAFConfig(GPIOC, GPIO_PinSource12, GPIO_AF_SPI3); // I2S3_SD
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource15, GPIO_AF_SPI3); // I2S3_WS
	GPIO_Init(GPIOA, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_15,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});
	GPIO_Init(GPIOC, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_10 | GPIO_Pin_12,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

	I2S_Init(SPI3, &(I2S_InitTypeDef) {
		.I2S_Mode = I2S_Mode_MasterTx,
		.I2S_Standard = I2S_Standard_Phillips,
		.I2S_DataFormat = I2S_DataFormat_16b,
		.I2S_MCLKOutput = I2S_MCLKOutput_Disable,
		.I2S_AudioFreq = I2S_AudioFreq_48k,
		.I2S_CPOL = I2S_CPOL_Low
	});
	I2S_Cmd(SPI3, ENABLE);


	// Display something
	tft_data((uint8_t[]){0x01}, 1, 1); // reset
	for(;;) {
		tft_data((uint8_t[]){0x29}, 1, 1); // display on
		tft_data((uint8_t[]){0x3A, 0x05}, 2, 1); // pixel format: 16 bit / pixel

		tft_data((uint8_t[]){ 0x2A, 0x00, 0x00, 0x01, 0x00 }, 4, 1 ); // column address set
		tft_data((uint8_t[]){ 0x2B, 0x00, 0x00, 0x01, 0x00 }, 4, 1 ); // row address set*/

		uint8_t tftdata[1000];
		tftdata[0] = 0x2C; // memory write command
		int i;
		for(i = 1; i < 1000; i++)
			tftdata[i] = i;
		tft_data(tftdata, 1000, 1);
	}

	uint16_t audio = 0;
	for(;;) {
		//print("a");
		while(!SPI_I2S_GetFlagStatus(SPI2, SPI_I2S_FLAG_TXE));
		SPI_I2S_SendData(SPI2, audio);
		SPI_I2S_SendData(SPI3, -audio);
		SPI_I2S_SendData(SPI1, 0x55);
		audio += 1234;
	}
	return 0;
}

void _exit(__attribute__((unused)) int asdf) {
	for(;;);
}
