#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_i2c.h"

// SI5351 register map generated by ClockBuilder
// (only for initial test, probably not going to be actually used)
#define code
#include "register_map.h"
#undef code

void SystemInit() {
}

int reg_i;
uint8_t a = 0x60;

int i2cdelay = 20;
void i2c_delay() {
	int d;
	for(d = 0; d < i2cdelay; d++) __asm("nop");
}

// SCL 8, SDA 9
#define I2C_SCL 0x100
#define I2C_SDA 0x200

void writereg(uint8_t addr, uint8_t reg, uint8_t v) {
	int i;
	uint32_t odr = GPIOB->ODR & (~(I2C_SCL | I2C_SDA));
	uint32_t allbits;
	// start
	GPIOB->ODR = odr | I2C_SCL;
	i2c_delay();
	GPIOB->ODR = odr;
	i2c_delay();

	allbits =
	(addr << (9*2+2)) | (0 << (9*2+1)) | (1 << (9*2)) |
	(reg  << (9*1+1)) |                  (1 << (9*1)) |
	(v    << (9*0+1)) |                  (1 << (9*0));
	for(i = 0; i < 9*3; i++) {
		uint32_t odr_bit;
		if(allbits & (1 << (9*3-1)))
			odr_bit = odr | I2C_SDA;
		else
			odr_bit = odr;
		allbits <<= 1;
		// send bit
		GPIOB->ODR = odr_bit;
		i2c_delay();
		GPIOB->ODR = odr_bit | I2C_SCL;
		i2c_delay();
		GPIOB->ODR = odr_bit;
		i2c_delay();
	}

	// stop
	GPIOB->ODR = odr | I2C_SCL;
	i2c_delay();
	GPIOB->ODR = odr | I2C_SCL | I2C_SDA;
	i2c_delay();
}


int main() {
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_I2C1, ENABLE);

	GPIO_Init(GPIOA, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

	GPIO_Init(GPIOB, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_8 | GPIO_Pin_9,
		.GPIO_Mode = GPIO_Mode_OUT,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_OD,
		.GPIO_PuPd = GPIO_PuPd_UP
	});

	GPIO_PinAFConfig(GPIOA, GPIO_PinSource5, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource6, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource7, GPIO_AF_SPI1);

	SPI_Init(SPI1, &(SPI_InitTypeDef) {
		.SPI_Direction = SPI_Direction_1Line_Tx,
		.SPI_Mode = SPI_Mode_Master,
		.SPI_DataSize = SPI_DataSize_8b,
		.SPI_CPOL = SPI_CPOL_Low,
		.SPI_CPHA = SPI_CPHA_1Edge,
		.SPI_NSS = SPI_NSS_Soft,
		.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_16,
		.SPI_FirstBit = SPI_FirstBit_MSB,
		.SPI_CRCPolynomial = 0
	});
	SPI_Cmd(SPI1, ENABLE);

	for(;;) {
		for(reg_i = 0; reg_i < NUM_REGS_MAX; reg_i++) {
			SPI_I2S_SendData(SPI1, 0x55);
			writereg(a, Reg_Store[reg_i].Reg_Addr, Reg_Store[reg_i].Reg_Val);
		}
	}
	return 0;
}

void _exit(__attribute__((unused)) int asdf) {
	for(;;);
}
