#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_i2c.h"

// SI5351 register map generated by ClockBuilder
// (only for initial test, probably not going to be actually used)
#define code
#include "register_map.h"
#undef code

void SystemInit() {
}

int i;
int i2cdelay = 2000;
uint8_t a = 0x60;

#if 0
void i2c_wait() {
	int d;
	//while(I2C_GetFlagStatus(I2C1, I2C_FLAG_BUSY));
	// let's see if it works more easily with fixed delay
	for(d = 0; d < i2cdelay; d++) __asm("nop");
}

/* trying to do something similar to
   https://github.com/Catethysis/stm32_i2c/blob/master/I2C.c
   - still doesn't work :( */
void writereg(uint8_t addr, uint8_t reg, uint8_t v) {
	I2C_GenerateSTART(I2C1, ENABLE);
	/*i2c_wait();
	I2C_GenerateSTART(I2C1, DISABLE);
	i2c_wait();*/
	while(!I2C_CheckEvent(I2C1, I2C_EVENT_MASTER_MODE_SELECT));

	I2C_Send7bitAddress(I2C1, addr, I2C_Direction_Transmitter);
	//i2c_wait();
	while(!I2C_CheckEvent(I2C1, I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED));

	I2C_SendData(I2C1, addr<<1);
	//i2c_wait();
	while(!I2C_CheckEvent(I2C1, I2C_EVENT_MASTER_BYTE_TRANSMITTED));

	I2C_SendData(I2C1, reg);
	//i2c_wait();
	while(!I2C_CheckEvent(I2C1, I2C_EVENT_MASTER_BYTE_TRANSMITTED));

	I2C_SendData(I2C1, v);
	//i2c_wait();
	while(!I2C_CheckEvent(I2C1, I2C_EVENT_MASTER_BYTE_TRANSMITTED));

	I2C_GenerateSTOP(I2C1, ENABLE);
	/*i2c_wait();
	I2C_GenerateSTOP(I2C1, DISABLE);
	i2c_wait();*/
	while(I2C_GetFlagStatus(I2C1, I2C_FLAG_BUSY));
}
#endif
#include "i2c.h"
void writereg(uint8_t addr, uint8_t reg, uint8_t v) {
	I2C_start(I2C1, addr, I2C_Direction_Transmitter);
	I2C_write(I2C1, reg);
	I2C_write(I2C1, v);
	I2C_stop(I2C1);
}


int main() {
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_I2C1, ENABLE);

	GPIO_Init(GPIOA, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_PP,
		.GPIO_PuPd = GPIO_PuPd_NOPULL
	});

#if 0
	GPIO_Init(GPIOB, &(GPIO_InitTypeDef) {
		.GPIO_Pin = GPIO_Pin_8 | GPIO_Pin_9,
		.GPIO_Mode = GPIO_Mode_AF,
		.GPIO_Speed = GPIO_Speed_50MHz,
		.GPIO_OType = GPIO_OType_OD,
		.GPIO_PuPd = GPIO_PuPd_UP
	});
#endif

	GPIO_PinAFConfig(GPIOA, GPIO_PinSource5, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource6, GPIO_AF_SPI1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource7, GPIO_AF_SPI1);

#if 0
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource8, GPIO_AF_I2C1);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource9, GPIO_AF_I2C1);
#endif

	SPI_Init(SPI1, &(SPI_InitTypeDef) {
		.SPI_Direction = SPI_Direction_1Line_Tx,
		.SPI_Mode = SPI_Mode_Master,
		.SPI_DataSize = SPI_DataSize_8b,
		.SPI_CPOL = SPI_CPOL_Low,
		.SPI_CPHA = SPI_CPHA_1Edge,
		.SPI_NSS = SPI_NSS_Soft,
		.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_16,
		.SPI_FirstBit = SPI_FirstBit_MSB,
		.SPI_CRCPolynomial = 0
	});
	SPI_Cmd(SPI1, ENABLE);

#if 0
	I2C_InitTypeDef i2ci;
	I2C_StructInit(&i2ci);
	i2ci.I2C_ClockSpeed = 100000;
	i2ci.I2C_Mode = I2C_Mode_I2C;
	i2ci.I2C_DutyCycle = I2C_DutyCycle_2;
	i2ci.I2C_Ack = I2C_Ack_Disable;
	i2ci.I2C_AcknowledgedAddress = I2C_AcknowledgedAddress_7bit;
	I2C_Init(I2C1, &i2ci);
	I2C_Cmd(I2C1, ENABLE);
#endif
	init_I2C1();

	for(;;) {
		for(i = 0; i < NUM_REGS_MAX; i++) {
			SPI_I2S_SendData(SPI1, 0x55);
			writereg(a, Reg_Store[i].Reg_Addr, Reg_Store[i].Reg_Val);
		}
		//a++; // try all addresses
	}
	return 0;
}

void _exit(__attribute__((unused)) int asdf) {
	for(;;);
}
